version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - '3004:3004'
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
      - PAYOS_API_KEY=${PAYOS_API_KEY}
      - PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}
      - PAYOS_ENVIRONMENT=${PAYOS_ENVIRONMENT:-sandbox}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - DEFAULT_RETURN_URL=${DEFAULT_RETURN_URL}
      - DEFAULT_CANCEL_URL=${DEFAULT_CANCEL_URL}
    restart: unless-stopped
    networks:
      - edu-forge-network
    command: >
      sh -c "until nc -z postgres 5432; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready!';
      npx prisma db push deploy && node dist/main.js"

  postgres:
    image: postgres:17
    container_name: edu-forge-payment-db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changed to avoid conflict with enrollment service
    restart: unless-stopped
    networks:
      - edu-forge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  edu-forge-network:
    driver: bridge




